# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  xcode14:
    name: "Xcode 14"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.25.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Swift Coverage Conversion
      uses: sersoft-gmbh/swift-coverage-action@v4.0.0
      id: coverage-files
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
